### ISSUE TITLE
Version not found: error 992

### ISSUE THREAD

**Issue by vfxdx** [Cesare0328/RBXM#1]
basically it can't detect what version i'm using for UWP, even though i have 2.92.586.0 installed, here's an image to show you what i mean
![image_2023-10-14_171336516](https://github.com/Cesare0328/RBXM/assets/147826612/bcb828d2-fc88-456c-ac6f-a6a9d4e1eb33)

**Comment by BaconDave312** [comment]
dont use this, the dude is a complete skid. he stole cerealwithmilk's code and put it here without credit.
https://github.com/cerealwithmilk/uwp/releases/tag/test
use this instead.

**Comment by BaconDave312** [comment]
if you are an exp use the fiddler classic method from their dis
https://discord.gg/cereal

**Comment by ZorkIsEmo** [comment]
> dont use this, the dude is a complete skid. he stole cerealwithmilk's code and put it here without credit. https://github.com/cerealwithmilk/uwp/releases/tag/test use this instead.

proven incorrect

**Comment by vfxdx** [comment]
> dont use this, the dude is a complete skid. he stole cerealwithmilk's code and put it here without credit. https://github.com/cerealwithmilk/uwp/releases/tag/test use this instead.

I also tried fluster, and the automated fluster version, they just show me this afterwards
![image](https://github.com/Cesare0328/RBXM/assets/147826612/5be4fc59-fe9a-47f2-9874-cb4fb1e1262f)

**Comment by Cesare0328** [comment]
Hi, this error is caused due to Roblox not loading in time, to fix this run your Roblox instance first then run Roblox Modder(This will be fixed on the next update).

**Comment by Cesare0328** [comment]
> basically it can't detect what version i'm using for UWP, even though i have 2.92.586.0 installed, here's an image to show you what i mean ![image_2023-10-14_171336516](https://user-images.githubusercontent.com/147826612/275243651-bcb828d2-fc88-456c-ac6f-a6a9d4e1eb33.png)

This is fully fixed for version [1.1](https://github.com/Cesare0328/RBXM/releases/tag/v1.1)
